id: nbw_youth_application_waiver
label: NBW YOUTH APPLICATION WAIVER
tags:
  - NBW
source:
  constants:
    'true': true
    black: black
    white: white
    latinx: latinx
    asian: asian
    native: native
    other: other
  plugin: csv
  path: '/var/www/YBEEP REPORTS - FYALL.csv'
  ids: [GUARDIAN_EMAILS,Timestamp]
process:
  webform_id:
    - plugin: default_value
      default_value: nbw_youth_application_waiver
  uid:
    - plugin: default_value
      default_value: 1
  remote_addr:
    - plugin: default_value
      default_value: '127.0.0.1'
  in_draft:
    - plugin: default_value
      default_value: 0
  locked:
    - plugin: default_value
      default_value: 0
  sticky:
    - plugin: default_value
      default_value: 0
  langcode:
    - plugin: default_value
      default_value: en
  uri:
    - plugin: default_value
      default_value: '/form/nbw-youth-application-waiver'
  # webform datas
  'data/date_of_birth':
    - plugin: format_date
      source: DOB
      from_format: 'n/j/y'
      to_format: 'Y-m-d'
  'data/male':
    - plugin: static_map
      source: GENDER
      map:
        male: 1
      default_value: 0
  'data/female':
    - plugin: static_map
      source: GENDER
      map:
        female: 1
      default_value: 0
  'data/transgender':
    - plugin: static_map
      source: GENDER
      map:
        transgender: 1
      default_value: 0
  'data/nonconforming':
    - plugin: static_map
      source: GENDER
      map:
        nonconforming: 1
      default_value: 0
  # races
  _race_sources:
    plugin: get
    source:
      - RACE1
      - RACE2
  'data/black_or_african_american':
    plugin: callback
    callable: in_array
    unpack_source: true
    source:
      - 'constants/black'
      - '@_race_sources'
      - 'constants/true'
  'data/white_or_caucasian':
    plugin: callback
    callable: in_array
    unpack_source: true
    source:
      - 'constants/white'
      - '@_race_sources'
      - 'constants/true'
  'data/hispanic_or_latinx':
    plugin: callback
    callable: in_array
    unpack_source: true
    source:
      - 'constants/latinx'
      - '@_race_sources'
      - 'constants/true'
  'data/asian':
    plugin: callback
    callable: in_array
    unpack_source: true
    source:
      - 'constants/asian'
      - '@_race_sources'
      - 'constants/true'
  'data/american_indian_or_alaska_native':
    plugin: callback
    callable: in_array
    unpack_source: true
    source:
      - 'constants/native'
      - '@_race_sources'
      - 'constants/true'
  'data/native_hawaiian_or_other_pacific_islander':
    plugin: callback
    callable: in_array
    unpack_source: true
    source:
      - 'constants/other'
      - '@_race_sources'
      - 'constants/true'
  'data/email': GUARDIAN_EMAILS
  'data/guardian_address/country_code':
    - plugin: default_value
      default_value: US
  'data/guardian_address/locality': ADDRESS_CITY
destination:
  plugin: 'entity:webform_submission'
