status: 1
pattern: 'Graduation Record for for Students [node:field_students] class [node:field_class_name] on [node:created:short]; updated on [node:changed:short]'
escape: false
preserve_titles: false
save: false
chunk: 50
dependencies:
  config:
    - node.type.graduation_record
