status: 1
pattern: 'Attendance recorded for Students [node:field_students] class [node:field_class_name] on [node:created:short]; updated on [node:changed:short]'
escape: false
preserve_titles: false
save: false
chunk: 50
dependencies:
  config:
    - node.type.attendance_record
new_content_behavior: 1
