status: 1
pattern: '[node:field_class_name] session on [node:created:short]; updated on [node:changed:short]'
escape: false
preserve_titles: false
save: false
chunk: 50
dependencies:
  config:
    - node.type.class_session_record
new_content_behavior: 1
