_core:
  default_config_hash: Lmq0hGaFh0zNyozQ2r61-vypLNm7zYcmI6DhSwV5cGU
enabled: true
expire_password: false
first_time_login_password_change: false
installation_date: 1708702491
check_login_only: false
