<?php

/**
 * @file
 * Primary module hooks for NBW tools module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_views_data_alter().
 */
function nbw_tools_field_views_data_alter(array &$data, \Drupal\field\FieldStorageConfigInterface $field_storage) {
  if ($field_storage->getType() === 'timestamp') {
    foreach ($data as $table_name => $table_data) {
      foreach ($table_data as $field_name => $field_data) {
        if (isset($field_data['filter']) && $field_data['filter']['id'] === 'numeric') {
          $data[$table_name][$field_name]['filter']['id'] = 'date';
        }
      }
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function nbw_tools_theme_suggestions_views_view_field(array $variables) {
  $suggestions = [];
  $suggestions[] = 'views_view_field__' . $variables['view']->id();
  $suggestions[] = 'views_view_field__' . $variables['view']->id() . '__' . $variables['field']->field;
  $suggestions[] = 'views_view_field__' . $variables['field']->field;
  return $suggestions;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function nbw_tools_form_webform_submission_sign_in_for_class_add_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['elements']['class']['#ajax'] = [
    'callback' => 'nbw_tools_webform_ajax_students',
    'wrapper' => 'students-container',
  ];
  $form['elements']['students']['#prefix'] = '<div id="students-container">';
  $form['elements']['students']['#suffix'] = '</div>';
}


/**
 * Return with students container.
 */
function nbw_tools_webform_ajax_students($form, FormStateInterface $form_state) {
  return $form['elements']['students'];
}
